# Generated by Django 6.0 on 2025-12-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='clicks',
        ),
    ]
