# Generated by Django 6.0 on 2025-12-13 03:58

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(default=shortener.models.generate_short_code, max_length=15, unique=True),
        ),
    ]
