# Generated by Django 6.0 on 2026-06-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_link_short_code_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
