# Generated by Django 6.0 on 2026-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkey',
            name='aaguid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
