# Generated by Django 6.0 on 2026-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_passkey_aaguid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_login_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
