"""
Django settings for zlink project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '*').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [f'{scheme}://{host}' for host in ALLOWED_HOSTS if host not in ['*', 'localhost', '127.0.0.1'] for scheme in ['https', 'http']]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'shortener.apps.ShortenerConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zlink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # required for Django admin templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zlink.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DATABASE', 'neondb'),
            'USER': os.getenv('POSTGRES_USER', 'neondb_owner'),
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.getenv('DB_PORT', 5432),
            'OPTIONS': {
                # 'require' for managed/cloud Postgres; set DB_SSLMODE=disable for local dev.
                'sslmode': os.getenv('DB_SSLMODE', 'require'),
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Redis Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'VERSION': 0,
    }
}

_cache_ttl_raw = os.getenv('CACHE_TTL')
CACHE_TTL = None if _cache_ttl_raw in (None, 'None', 'none', '') else int(_cache_ttl_raw)

# Note: short-link redirect resolution and GA4 click tracking are handled by
# the Go client (ZLinkClient); this Django service is the management API only.

# Django REST Framework
# https://www.django-rest-framework.org/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', 15))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', 7))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Public base URL of the redirect service (ZLinkClient / Go). Used to build the
# clickable short links shown in the admin UI. Falls back to the request host
# when unset (fine for local dev, wrong in production where Go has its own domain).
SHORT_LINK_BASE_URL = os.getenv('SHORT_LINK_BASE_URL', '').rstrip('/')

# Frontend (ZLinkFE) domain(s) allowed to call the API. Enter bare domains,
# comma-separated, e.g. "example.com, test.com". Each is expanded to both
# https:// and http:// origins for the CORS allow-list.
# https://github.com/adamchainz/django-cors-headers
FRONTEND_URL = os.getenv('FRONTEND_URL', '')


def _domains_to_origins(raw):
    origins = []
    for item in raw.split(','):
        host = item.strip().rstrip('/')
        if not host:
            continue
        if '://' in host:
            origins.append(host)  # a full origin was given; use as-is
        else:
            origins.extend(f'{scheme}://{host}' for scheme in ('https', 'http'))
    return origins


# Dev default: the Angular dev server when no FRONTEND_URL is configured.
CORS_ALLOWED_ORIGINS = _domains_to_origins(FRONTEND_URL) or [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]
CORS_ALLOW_CREDENTIALS = False

# WebAuthn (passkeys). The "Relying Party" ID is the bare domain the SPA is
# served from (passkeys are scoped to the page's effective domain, not the
# API's domain). Defaults to the first FRONTEND_URL entry; override directly
# if that heuristic doesn't fit a deployment (e.g. RP ID needs to be a parent
# domain shared across subdomains).
_first_frontend_domain = next(
    (d.strip().rstrip('/').split('://')[-1] for d in FRONTEND_URL.split(',') if d.strip()), ''
)
WEBAUTHN_RP_ID = os.getenv('WEBAUTHN_RP_ID', '') or _first_frontend_domain or 'localhost'
WEBAUTHN_RP_NAME = 'ZLink'
WEBAUTHN_ORIGINS = CORS_ALLOWED_ORIGINS

# drf-spectacular (OpenAPI schema)
SPECTACULAR_SETTINGS = {
    'TITLE': 'ZLink API',
    'DESCRIPTION': 'Management API for the ZLink URL shortener.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Only Django admin's own static files are collected now (no custom frontend).
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

DEFAULT_SUPERUSER_USERNAME = os.getenv('DEFAULT_SUPERUSER_USERNAME', 'ZLink')
DEFAULT_SUPERUSER_EMAIL = os.getenv('DEFAULT_SUPERUSER_EMAIL', 'zlink@zhiu.dev')
DEFAULT_SUPERUSER_PASSWORD = os.getenv('DEFAULT_SUPERUSER_PASSWORD', 'ZLink')